server:
  port: 8082

spring:
  datasource:
    saga:
      driver-class: com.alibaba.druid.proxy.DruidDriver
      url: jdbc:mysql://192.168.202.1:3306/seata_saga
      username: 11
      password: 121
  application:
    name: seata-saga-tm-feign

eureka:
  client:
    service-url:
      defaultZone: http://192.168.202.1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# Ribbon
ribbon:
  ReadTimeout: 20000 # 请求处理的超时时间
  ConnectTimeout: 10000 # 请求连接的超时时间
  #MaxAutoRetries: 0
  #OkToRetryOnAllOperations: false #Whether all operations can be retried for this client
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

#====================================Seata Config===============================================
## Seata接入
seata:
  # 关闭自动代理
  enable-auto-data-source-proxy: false
  ## 配置中心采用apollo
  config:
    type: apollo
    apollo:
      apollo-meta: http://127.0.0.0.1
      app-id: seata-demo
      namespace: framework.seata-common
  ## 注册中心采用redis
  registry:
    type: eureka
    eureka:
      application: seata-server
      service-url: http://192.168.202.1:8761/eureka
  tx-service-group: my_test_tx_group
